### ISSUE TITLE
csvファイルのスペルミス

### ISSUE THREAD

**Issue by Kerval12434** [takao-t/asterisk-sound-ja#1]
翻訳ありがとうございます。自作のpythonスクリプト噛ませてボイスボックスと利用しています。
本当はプルリクした方がいいと思うのですが、1か所だけですので…

core-sounds-ja.csv
誤: `469 ,vm-repaet,このメッセージをもう一度再生するには５を押してください。`
正: `469 ,vm-repeat,このメッセージをもう一度再生するには５を押してください。`

もしワザとぼかしているようでしたら藪蛇ですいません。。。

**Comment by takao-t** [comment]
ありがとうございます。修正しました。
ミスの指摘等は大変たすかります。
